const tableData = [
  { id: 1, name: "Aarav Sharma", age: 28, email: "aarav.sharma@example.com", salary: 50000 },
  { id: 2, name: "Vivaan Singh", age: 34, email: "vivaan.singh@example.com", salary: 60000 },
  { id: 3, name: "Aditya Nair", age: 45, email: "aditya.nair@example.com", salary: 75000 },
  { id: 4, name: "Ananya Gupta", age: 29, email: "ananya.gupta@example.com", salary: 52000 },
  { id: 5, name: "Vihaan Khanna", age: 38, email: "vihaan.khanna@example.com", salary: 68000 },
  { id: 6, name: "Diya Iyer", age: 25, email: "diya.iyer@example.com", salary: 48000 },
  { id: 7, name: "Aadhya Reddy", age: 32, email: "aadhya.reddy@example.com", salary: 59000 },
  { id: 8, name: "Krishna Patil", age: 41, email: "krishna.patil@example.com", salary: 72000 },
  { id: 9, name: "Sara Rao", age: 27, email: "sara.rao@example.com", salary: 51000 },
  { id: 10, name: "Aryan Chatterjee", age: 36, email: "aryan.chatterjee@example.com", salary: 64000 },
  { id: 11, name: "Kavya Kapoor", age: 30, email: "kavya.kapoor@example.com", salary: 55000 },
  { id: 12, name: "Ishaan Mehta", age: 33, email: "ishaan.mehta@example.com", salary: 62000 },
  { id: 13, name: "Myra Joshi", age: 40, email: "myra.joshi@example.com", salary: 71000 },
  { id: 14, name: "Aanya Pillai", age: 22, email: "aanya.pillai@example.com", salary: 47000 },
  { id: 15, name: "Kabir Kulkarni", age: 29, email: "kabir.kulkarni@example.com", salary: 53000 },
  { id: 16, name: "Anika Malhotra", age: 31, email: "anika.malhotra@example.com", salary: 56000 },
  { id: 17, name: "Aarohi Deshmukh", age: 26, email: "aarohi.deshmukh@example.com", salary: 49000 },
  { id: 18, name: "Arjun Bajaj", age: 35, email: "arjun.bajaj@example.com", salary: 65000 },
  { id: 19, name: "Riya Menon", age: 37, email: "riya.menon@example.com", salary: 67000 },
  { id: 20, name: "Dhruv Pandey", age: 28, email: "dhruv.pandey@example.com", salary: 52000 },
  { id: 21, name: "Saanvi Das", age: 32, email: "saanvi.das@example.com", salary: 59000 },
  { id: 22, name: "Anaya Roy", age: 39, email: "anaya.roy@example.com", salary: 70000 },
  { id: 23, name: "Neeraj Bhatt", age: 24, email: "neeraj.bhatt@example.com", salary: 48000 },
  { id: 24, name: "Mira Sen", age: 31, email: "mira.sen@example.com", salary: 56000 },
  { id: 25, name: "Arnav Aggarwal", age: 33, email: "arnav.aggarwal@example.com", salary: 63000 },
  { id: 26, name: "Rishabh Verma", age: 30, email: "rishabh.verma@example.com", salary: 54000 },
  { id: 27, name: "Lakshmi Sinha", age: 42, email: "lakshmi.sinha@example.com", salary: 74000 },
  { id: 28, name: "Nisha Jain", age: 27, email: "nisha.jain@example.com", salary: 51000 },
  { id: 29, name: "Aman Kaur", age: 36, email: "aman.kaur@example.com", salary: 66000 },
  { id: 30, name: "Rajesh Singh", age: 34, email: "rajesh.singh@example.com", salary: 62000 }
];

export default tableData;
